name: Sync README

on:
  push:
    branches:
      - main
    paths:
      - 'links.json'
      - 'README.tpl.md'
      - 'scripts/render_readme.py'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Render README from template
        run: |
          python scripts/render_readme.py

      - name: Commit updated README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README from template" || echo "No changes to commit"
          git push || echo "Push skipped"
